// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArlrjS97LI7CtIzS3irBr_gl1XugCzAKY',
    appId: '1:1069303037829:web:338ba54e47670b8e2b8eec',
    messagingSenderId: '1069303037829',
    projectId: 'shoppingapp-3b95d',
    authDomain: 'shoppingapp-3b95d.firebaseapp.com',
    storageBucket: 'shoppingapp-3b95d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojTEawde73WpsTekGBBL0jiDkf4--JrM',
    appId: '1:1069303037829:android:f0da25abe68675202b8eec',
    messagingSenderId: '1069303037829',
    projectId: 'shoppingapp-3b95d',
    storageBucket: 'shoppingapp-3b95d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrlx1t-CB7YFUZ8PzKcSDGYlgEa9JV1gI',
    appId: '1:1069303037829:ios:297080d5a6ff97ab2b8eec',
    messagingSenderId: '1069303037829',
    projectId: 'shoppingapp-3b95d',
    storageBucket: 'shoppingapp-3b95d.appspot.com',
    iosClientId: '1069303037829-kpohjn4h3jt2s0tf2vbltgjgq1squk23.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrlx1t-CB7YFUZ8PzKcSDGYlgEa9JV1gI',
    appId: '1:1069303037829:ios:297080d5a6ff97ab2b8eec',
    messagingSenderId: '1069303037829',
    projectId: 'shoppingapp-3b95d',
    storageBucket: 'shoppingapp-3b95d.appspot.com',
    iosClientId: '1069303037829-kpohjn4h3jt2s0tf2vbltgjgq1squk23.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
